apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: na1m1f4fq-dotnet-basic
  janus-idp.io/tekton: na1m1f4fq-dotnet-basic
  backstage.io/kubernetes-id: na1m1f4fq-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: na1m1f4fq-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
